global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: ['proxy:8082']
  - job_name: nuxt
    static_configs:
      - targets: ['server:3000']
  - job_name: mysql
    params:
      # Not required. Will match value to child in config file. Default value is `client`.
      auth_module: [client]
    static_configs:
      - targets:
        # All mysql hostnames or unix sockets to monitor.
        - database:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # The mysqld_exporter host:port
        replacement: mysql-exporter:9104